---

- add_host:
    name: initiator
    ansible_host: "{{ cloud_vpn_initiator_public_ip }}"
    ansible_user: "{{ cloud_vpn_initiator_user }}"
    ansible_connection: "{{ cloud_vpn_initiator_ansible_connection }}"
    ansible_network_os: ios
    ansible_ssh_private_key_file: "{{ cloud_vpn_initiator_ssh_private_key_file }}"

- name: Wait for SSH port to be reachable
  wait_for:
    host: "{{ cloud_vpn_initiator_public_ip }}"
    port: 22

- name: Pause for SSH daemon to settle and accept connections
  pause:
    seconds: "{{ cloud_vpn_pause_before_config_seconds }}"

